### ISSUE TITLE
Header row only issue

### ISSUE THREAD

**Issue by tschlarm** [AndrewRissing/GenericParsing#1]
If there is only a header row in the csv file, but it has a <CR><LF> at the end of the row then no columns are returned. 

This differs slightly from the unit test "HeaderRowWithoutData()" in that if you add a "\r\n" at the end of the StringReader the test will fail.

I haven't figured out a fix for it yet, but I thought I'd report it.

**Comment by AndrewRissing** [comment]
I've just uploaded 1.1.5.  Sorry, I never got notified for this issue.
