### ISSUE TITLE
Generic Parser throws exception when FirstRowHasHeader set to false while reading file.

### ISSUE THREAD

**Issue by V-bikunj** [AndrewRissing/GenericParsing#14]
I have updated the Generic Parser to the latest version but it it throwing error while we set FirstRowHasHeader as false to read the file it is working fine when we set it to true.

Please find the code for reference. 
using (GenericParser parser = new GenericParser(TextFile)
            {
                
                parser.FirstRowHasHeader = false;
                
                parser.FirstRowSetsExpectedColumnCount = true;
                parser.MaxBufferSize = 4 * 1024; // 4 KB
                parser.MaxRows = 500;

Please let me know if you need any further details.

**Comment by AndrewRissing** [comment]
Can you provide an example of the data that causes the issue when combined with the configuration above?

FirstRowHasHeader just tells the parser to use the first row's data for header names.  Setting it to false should have no negative side effects.

**Comment by AndrewRissing** [comment]
I've just verified the correct behavior with the following [LinqPad](https://www.linqpad.net/) script:

```
void Main()
{
	var input = "a,b,c\n\r1,2,3\n\r4,5,6";

	using (var sr = new StringReader(input))
	using (var parser = new GenericParserAdapter(sr))
	{
		parser.FirstRowHasHeader = true;
		parser.FirstRowSetsExpectedColumnCount = true;
		parser.MaxBufferSize = 4 * 1024; // 4 KB
		parser.MaxRows = 500;

		parser.GetDataSet().Dump("With Header Row");
	}

	using (var sr = new StringReader(input))
	using (var parser = new GenericParserAdapter(sr))
	{
		parser.FirstRowHasHeader = false;
		parser.FirstRowSetsExpectedColumnCount = true;
		parser.MaxBufferSize = 4 * 1024; // 4 KB
		parser.MaxRows = 500;

		parser.GetDataSet().Dump("Without Header Row");
	}
}
```

I don't see any issues.  Please check your code and your inputs to sort out the problem.  If you feel there is indeed an issue, please post back with more specifics and we'll go from there.

As a side note, I'm only using the GenericParserAdapter to leverage the `GetDataSet` method to make the example easier to inspect.  It derives from GenericParser to add the additional features.

**Comment by V-bikunj** [comment]
Andrew can you please look into below code it is not working. you can take any text file and try to run for true case running fine but for false it is throwing error. 
static void Main(string[] args)
        {
            List<Dictionary<string, string>> fileData = new List<Dictionary<string, string>>();
            string path = @"C:\Documents\Generic\Storetable.txt";
            TextReader SFTPTextReader = new StreamReader(path);

            using (GenericParserAdapter parser = new GenericParserAdapter(SFTPTextReader))
            {
                
                parser.FirstRowHasHeader = false;  // for true working fine
               
                parser.FirstRowSetsExpectedColumnCount = true;
                parser.MaxBufferSize = 4 * 1024; // 4 KB
                parser.MaxRows = 5;

                while (parser.Read())
                {
                    Dictionary<string, string> fileRow = new Dictionary<string, string>();

                    for (int i = 0; i < parser.ColumnCount; i++)
                    {

                        fileRow.Add(parser.GetColumnName(i), parser[i]);

                    }
                    fileData.Add(fileRow);
                }
            }
            if (fileData.Count == 0)
            {
                Console.WriteLine("True");
                Console.ReadLine();
            }
            else
            {
                Console.WriteLine("false");
                Console.ReadLine();
            }
        }

**Comment by AndrewRissing** [comment]
You must set `FirstRowHasHeader` to true for a column name to be set.
