### ISSUE TITLE
Support for Other language Characters

### ISSUE THREAD

**Issue by rahul-nigam** [AndrewRissing/GenericParsing#15]
Objective - to import a CSV file into a dataset
Issue - My CSV file contains data from different languages (Other than English) which comes as an unknown character.
1st Image from CSV and 2nd after converting to the dataset.
![image](https://user-images.githubusercontent.com/46566933/89178666-c0439580-d5ab-11ea-888d-d604121ca5b0.png)

![image](https://user-images.githubusercontent.com/46566933/89178489-575c1d80-d5ab-11ea-8aaf-5762aac81c75.png)

**Comment by AndrewRissing** [comment]
Please try adjusting the Encoding passed into the [GenericParser](https://github.com/AndrewRissing/GenericParsing/blob/master/GenericParsing/GenericParser.cs#L216) like here or in the data source you provide.  The issue you're experiencing isn't with the parser itself, but the data source you're providing it.
