### ISSUE TITLE
Row parser column name does not support case insensitivity?

### ISSUE THREAD

**Issue by ejayhrnz** [AndrewRissing/GenericParsing#18]
For example: 

I have a column name "Date" and whenever I access or use it, this happens:

parser["Date"] <--- this will return a value

parser["DATE"] <--- but this will return null error

**Comment by AndrewRissing** [comment]
This is working as designed.

If you'd like to adjust the behavior, I'd recommend modifying [this method here](https://github.com/AndrewRissing/GenericParsing/blob/master/GenericParsing/GenericParser.cs#L2370).
