### ISSUE TITLE
Long Numeric data was shorten with scientific E+ like excel.

### ISSUE THREAD

**Issue by CSYKAIFA** [AndrewRissing/GenericParsing#19]
221000000000 read from csv will become  2.21E+11. How to keep it original TEXT?

**Comment by AndrewRissing** [comment]
I'm not sure.   This library only returns raw strings, so the issue must lie somewhere downstream from it.   I suggest looking at the results from the GenericParser directly on a slim down version of your input and tracking down the source of your issue.   Good luck.
