### ISSUE TITLE
Supports the ability to dynamically add more columns to match the data

### ISSUE THREAD

**Issue by wizardgsz** [AndrewRissing/GenericParsing#20]
Please may I have an example using this feature?

e.g. having fixed width parser and GenericParserAdapter, is it possible to have variable number of columns row by row?

row A: col 1, 2, 3, 4, 5, 6
row B: col 1, 2, 3, 4, 5
row C: col 1, 2, 3, 4, 5, 6, 7
...

Thanks a lot

**Comment by AndrewRissing** [comment]
Sorry, the code currently doesn't support this feature. 

You'd need to modify the behavior somewhere around [here](https://github.com/AndrewRissing/GenericParsing/blob/307aac598ec4aa4ab7fa01933469e24b2b354b3c/GenericParsing/GenericParser.cs#L1141)  to do so.

**Comment by AndrewRissing** [comment]
If you'd like to create a PR with tests, I can pull in the change.   Otherwise, I'll consider this closed.
