### ISSUE TITLE
How can we identify row or file is invalid csv

### ISSUE THREAD

**Issue by hytechpro-bikeshs** [AndrewRissing/GenericParsing#21]
I have two questions here.
1. I am using GenericParserAdapter but just want to know if extra separator in any row then can we have the option to know if this is the incorrect row? need line-by-line validation. see example
ABC|123|xyz
ABD||124|xyd   -this row has an extra separator so I need to consider it invalid line no also needed.
Could you please assist with this?

2. How can we know about field datatype, by default now showing string?

**Comment by AndrewRissing** [comment]
1.  If you're looking for row-by-row analysis, you probably want to use the `GenericParser` base class and iterate over each row to check the parsed inputs.  While doing that, you can verify the number of columns is what you expect (or alternatively use the `ExpectedColumnCount` to validate the number of columns) and take appropriate action if it doesn't meant expectations.
2.  The parser will only return back the parsed raw string from the columns.  It is up to you to convert the type to the expected data type.
