### ISSUE TITLE
Column name with ignoring case

### ISSUE THREAD

**Issue by jonataspc** [AndrewRissing/GenericParsing#22]
Hello,

Is there a way to configure the parser to accept sort of a StringComparison enum to ignore case when retrieving data by column name?

In other words, I would like to be able to get the same information using either ` string status = parser["Status"]`  or ` string status = parser["STATUS"]` , regardless the column name case in the source file.

Thanks.

**Comment by AndrewRissing** [comment]
Not today, but you'd be able to do by modifying [this right here](https://github.com/AndrewRissing/GenericParsing/blob/master/GenericParsing/GenericParser.cs#LL2370C1-L2370C1).  PRs will be accepted.

**Comment by jonataspc** [comment]
Done: https://github.com/AndrewRissing/GenericParsing/pull/23

**Comment by AndrewRissing** [comment]
I'll take a look this weekend.  If everything looks good, I'll merge and release it. 

Thanks.

**Comment by AndrewRissing** [comment]
Changes released - [v1.3.0](https://www.nuget.org/packages/GenericParsing/1.3.0).
