### ISSUE TITLE
Signed assembly

### ISSUE THREAD

**Issue by megaskills** [AndrewRissing/GenericParsing#24]
Hi Andrew

is it possible to get a version of this awesome tool as a signed assembly or its the preferred method to fork it and add our own certificate?

i have seen some other providers offer nameofproduct.signed on Nuget

fyi. any .net standard 2.0 libraries using the nuget version of GenericParsing wont compile if signing is enabled.

Regards
peter

**Comment by AndrewRissing** [comment]
Sure, I can look into that this weekend. 👍

**Comment by AndrewRissing** [comment]
@megaskills I've pushed up 1.5.0 to add the strong name.  In addition, I went ahead and added .NET 6/8.

https://www.nuget.org/packages/GenericParsing/1.5.0

Thanks for your interest in this old project.  I hope that helps.

Let me know if you have any other issues.

**Comment by megaskills** [comment]
Thanks Andrew. I really appreciate your effort in doing this.
