### ISSUE TITLE
GenericParser stream does not take into account large cells for csv files

### ISSUE THREAD

**Issue by dontloseyourheadsu** [AndrewRissing/GenericParsing#25]
The stream only uses the buffer properly when the rows for a csv file is too large but the contents of each cell is small.

Expected:
CSV Files with large cell contents are read by the stream properly

Actual:
ParsingException asking to increase the buffer size

**Comment by AndrewRissing** [comment]
@dontloseyourheadsu I'm not sure what your bug report is for.  If you can provide an example (or even better a test) that shows your issue, I can help.

As for now, I put together my own test to verify your concerns and didn't find any issue:

```csharp
[Fact]
public void BufferUsage_Issue25()
{
    var sb = new StringBuilder();
    sb.Append(new string('a', 100));
    sb.Append(',');
    sb.Append(new string('b', 100));
    sb.Append(',');
    sb.Append(new string('c', 100));
    sb.Append(',');
    sb.Append(new string('d', 100));

    using (var gp = new GenericParserAdapter())
    {
        using (var sr = new StringReader(sb.ToString()))
        {
            // Largest column size = 100
            // Row size = 400 + 3 = 403
            gp.MaxBufferSize = 110;
            gp.SetDataSource(sr);

            Assert.True(gp.Read());
            Assert.Equal(4, gp.ColumnCount);
        }
    }
}
```

The buffer size must be at least the size of a single column of data.  If you have large columns, you'll need to be sure to set the buffer size to something slightly larger than your largest column size.

If you can provide the test that represents your issue, I can look at resolving the bug.  At this time, I'm closing this as user error.
