### ISSUE TITLE
Text Qualifier

### ISSUE THREAD

**Issue by kevingy** [AndrewRissing/GenericParsing#3]
If I specify a text qualifier or use the default qualifier, should the qualifier be stripped or returned? For example, if the CSV file is:

```
Company,Street,City,State
"ABC, Inc.",123 Main St.,New York,New York
```

When I get the value of genericParser["Company"], I'm getting "\\"ABC, Inc.\\"". I can strip the qualifier, but if GenericParser can or is supposed to, I'd prefer that.

**Comment by AndrewRissing** [comment]
Using the snippet below, I'm not seeing any issue.  The resulting string is "[ABC, Inc.]", so the text qualifiers are removed properly.

I'll close this out, as I'm assuming that is what you're asking for.  Let me know if I'm missing the mark on something.

```
using (StringReader sr = new StringReader("Company,Street,City,State\n\r\"ABC, Inc.\",123 Main St.,New York,New York"))
using (GenericParser gp = new GenericParser(sr))
{
	gp.TextQualifier = '"';
	gp.FirstRowHasHeader = true;
	
	if (gp.Read())
	{
		Console.WriteLine($"[{gp["Company"]}]");
	}
}
```

**Comment by kevingy** [comment]
When I run your example, it works fine. You used exactly the data that I gave you. Unfortunately, I simplified the data for demonstration purposes. As it turns out, the data I gave you works fine. The actual data is tab delimited and read from a file. I updated your code and the data to account for being tab delimited, and it still works. It has to be something in reading from a file.

I'll fork the repository and see what I can figure out. If there is a code change, I'll submit a pull request.

You confirmed that the library should be stripping the text qualifier, which was really my initial question.

**Comment by AndrewRissing** [comment]
You might have bad data, which would be different issue entirely.

I've seen applications leverage Unicode quotes (”) vs. ("), so that might be your issue.  If that's the case, hopefully, your data won't contain tabs which were meant to be escaped with the quotes and then you'll just have to perform a post-process to strip out any "quote" like characters from the beginning/end.

Another avenue to check is that you're using the correct text encoding (there's a method overload for that), I've seen this crop up if your file doesn't have the right byte encoding at the start, which confuses the TextReader.

Good luck.  If you find something, either create a PR or provide a sample of the failure.  I can roll those changes into the signing that I'll do this weekend, if you can turn it around quick enough.

**Comment by kevingy** [comment]
I figured out how to reproduce it, with a slight modification to the above example. I'll paste the code from above with modifications to nothing except the CSV data:

```
using (StringReader sr = new StringReader("Company,Street,City,State\n\r\"ABC, Inc.\"          ,123 Main St.,New York,New York"))
using (GenericParser gp = new GenericParser(sr))
{
	gp.TextQualifier = '"';
	gp.FirstRowHasHeader = true;
	
	if (gp.Read())
	{
		Console.WriteLine($"[{gp["Company"]}]");
	}
}
```
Note the 10 spaces after the closing quote text qualifier before the comma closing the column.

While this is not my sample data set exactly, it demonstrates the problem with a simplified data set. This code will output:

```
["ABC, Inc."           ] 
```

If the extra spaces in the data are removed, it will output [ABC, Inc.] as previously found.

I'll keep looking to see if a change to the library can be made, probably in _ExtractColumn().

**Comment by AndrewRissing** [comment]
That's actually correct behavior.

You have malformed data.  The quotes must open at the start of the column and close at the end of the column.  Otherwise, it becomes non-deterministic in its behavior.

**Comment by kevingy** [comment]
I agree. Any change that I might make to the library would invalidate the library. I'll handle the malformed data in code. Looking more closely at the file, it's an odd mix of being tab-delimited and fixed width.

Thank your for your time to look at this..
