### ISSUE TITLE
copy CSV data into a datatable using the structure of the data to create the DataTable:

### ISSUE THREAD

**Issue by papyr** [AndrewRissing/GenericParsing#5]
Hi, can you share a snippet on how to bulk copy multiple files using the CSV headers/ structure and create th Datatable in sql server, I saw a ref. from [here ](https://stackoverflow.com/a/1050149/2635161)from SO, but no snippet

**Comment by AndrewRissing** [comment]
The article you referenced provides ample examples of how to parse data.  If you're specifically wanting something in the form of a DataSet/DataTable, I'd recommend looking at the GenericParserAdapter's GetDataSet/GetDataTable methods respectively.

As for the bigger picture question, I'm sorry there's plenty of resources out there for discussing how to do that.  The GenericParser is merely one piece of the puzzle for you to be able to do that.

Good luck.
