### ISSUE TITLE
The package does not contain any assembly references or content files that are compatible with that framework.

### ISSUE THREAD

**Issue by iturribeitia** [AndrewRissing/GenericParsing#7]
I was trying to replace the DEPRECATED GenericParser 1.1.6 with this GenericParsing 1.2.0
and I'm receiving this error:
Severity	Code	Description	Project	File	Line	Suppression State
Error		Could not install package 'GenericParsing 1.2.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5.2', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.			0	

Thanks.

**Comment by AndrewRissing** [comment]
[Give this a try](https://www.nuget.org/packages/GenericParsing/1.2.1).

If you have any issues, reopen the issue.

**Comment by iturribeitia** [comment]
> [Give this a try](https://www.nuget.org/packages/GenericParsing/1.2.1).
> 
> If you have any issues, reopen the issue.

Now It is working perfect !!! Thanks a lot, wonderful Parser !!!
