### ISSUE TITLE
Generic Parser Finding Extra Columns w/ Fixed Width Formats

### ISSUE THREAD

**Issue by 500lb-Bench** [AndrewRissing/GenericParsing#9]
Hi, I have the following fixed width configuration for an encoded file. The widths work with standard TextFieldParser but fails in generic parser because its expecting/found 12 columns? 

using (GenericParserAdapter _parserAdapter = new GenericParserAdapter(_filePath, Encoding.GetEncoding(37)))
            {
                _parserAdapter.ColumnWidths = new int[] {
                    11,
                    1, 
                    11,
                    4, 
                    11,
                    1, 
                    11,
                    2, 
                    26,
                    1, 
                    1, 
                };            
                _parserAdapter.TextFieldType = FieldType.FixedWidth;
                _parserAdapter.TrimResults = true;
                
                while (_parserAdapter.Read())
                {
                    var a = _parserAdapter[0];
                }
            }

It always fails on the following.

        private void _ExtractColumn(int intEndOfDataIndex)
        { ….
           if ((this.m_intExpectedColumnCount > 0) && (this.m_lstData.Count >- this.m_intExpectedColumnCount))
                throw this._CreateParsingException(string.Format("Current column {0} exceeds ExpectedColumnCount of {1}.",

I don't understand how this is occurring. Am I missing a config option or is this a defect?

Please help thanks.

**Comment by AndrewRissing** [comment]
You'd have to look at your input file to be sure it truly matches the fixed widths you're passing in (i.e. a total length of 80 characters).  If you find it does look right, can you post the complete row (or equivalent there of) that caused the issue, so that I could reproduce.

**Comment by 500lb-Bench** [comment]
Thanks for responding.

**Comment by 500lb-Bench** [comment]
I can shred it successfully in SQL Server SSIS also. It has an option to specify a "header row delimiter". {CR}{LF}

**Comment by AndrewRissing** [comment]
Your input file does not have any newlines/return characters in your file.

The parser expects lines of data to be separated by one of these characters.

At this point, it looks like you're using the wrong tool for the job or your input isn't formatted properly (unlikely due to your SSIS comment).

**Comment by 500lb-Bench** [comment]
Thanks a lot for taking the time on this. Sometimes it’s little things that get you.
